# Generated by Django 5.1.4 on 2025-01-14 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogphoto',
            options={},
        ),
        migrations.AlterField(
            model_name='blogphoto',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.blog'),
        ),
        migrations.AlterField(
            model_name='blogphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogphoto',
            name='photo',
            field=models.ImageField(upload_to='blog_photos/'),
        ),
    ]
