# Generated by Django 5.1.4 on 2025-01-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_gallery_galleryphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='updated_at',
        ),
    ]
