# Generated by Django 5.1.4 on 2025-01-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_sertificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sertificate',
            options={'verbose_name': 'Сертификаты'},
        ),
    ]
