# Generated by Django 5.0.4 on 2025-01-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Блог", "verbose_name_plural": "Блоги"},
        ),
    ]
