# Generated by Django 5.0.4 on 2025-01-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0015_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="sertificate",
            name="category",
            field=models.CharField(
                choices=[
                    ("fire_doors_cert", "Сертификаты на противопожарные двери"),
                    (
                        "aluminum_structures_cert",
                        "Сертификаты на алюминиевые конструкции",
                    ),
                    (
                        "smoke_proof_doors_cert",
                        "Сертификаты на дымогазонепроницаемые двери",
                    ),
                    ("product_cert", "Сертификаты на изделия"),
                    (
                        "installation_license",
                        "Лицензия на осуществление монтажных работ",
                    ),
                    ("certification_tests", "Протоколы сертификационных испытаний"),
                    ("gost_iso_cert", "Сертификат соответствия требованиям ГОСТ Р ИСО"),
                ],
                default=0,
                max_length=100,
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
    ]
