# Generated by Django 5.1.4 on 2025-01-30 13:29

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
